#!/usr/bin/env node
// Regenerate src/index.ts from src/components/*/index.ts (alphabetical, deterministic).
import { readdirSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const compDir = join(root, "src", "components");

const names = readdirSync(compDir, { withFileTypes: true })
  .filter((d) => d.isDirectory() && existsSync(join(compDir, d.name, "index.ts")))
  .map((d) => d.name)
  .sort((a, b) => a.localeCompare(b));

const header = `// Styles must load with the bundle (tokens + global + component CSS).
import "./styles/tokens.css";
import "./styles/global.css";

// ---- Components (barrel; generated by scripts/gen-barrel.mjs) ----
`;

const body = names.map((n) => `export * from "./components/${n}";`).join("\n");
writeFileSync(join(root, "src", "index.ts"), header + body + "\n");
console.log(`barrel: ${names.length} components ->\n  ${names.join("\n  ")}`);
