// Builds the per-component live-demo host into docs/public/embed/.
// Auto-discovers demo/cases/*.jsx, generates a registry, bundles with esbuild,
// and copies the library CSS. Output is served by VitePress at /prism-ds/embed/.
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { readdirSync, writeFileSync, copyFileSync, mkdirSync } from "node:fs";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const casesDir = resolve(here, "cases");
const out = resolve(root, "docs/public/embed");
mkdirSync(out, { recursive: true });

// 1. registry.js from the case files
const slugs = readdirSync(casesDir)
  .filter((f) => f.endsWith(".jsx"))
  .map((f) => f.replace(/\.jsx$/, ""))
  .sort();
const importLines = slugs.map((s) => `import c_${s.replace(/[^a-z0-9]/gi, "_")} from "./${s}.jsx";`).join("\n");
const mapLines = slugs.map((s) => `  ${JSON.stringify(s)}: c_${s.replace(/[^a-z0-9]/gi, "_")},`).join("\n");
writeFileSync(
  resolve(casesDir, "registry.js"),
  `// GENERATED by build-embed.mjs — do not edit.\n${importLines}\n\nexport default {\n${mapLines}\n};\n`,
);
console.log(`✓ registry: ${slugs.length} cases`);

// 2. bundle
const esbuild = resolve(root, "node_modules/.bin/esbuild");
execFileSync(esbuild, [
  "demo/embed.jsx",
  "--bundle",
  "--format=iife",
  "--jsx=automatic",
  "--minify",
  '--define:process.env.NODE_ENV="production"',
  "--target=es2020",
  `--outfile=${out}/embed.js`,
], { cwd: root, stdio: "inherit" });

// 3. assets
copyFileSync(resolve(root, "dist/index.css"), resolve(out, "prism.css"));
copyFileSync(resolve(here, "embed.css"), resolve(out, "embed.css"));
writeFileSync(
  resolve(out, "index.html"),
  `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="color-scheme" content="light dark" />
    <link rel="stylesheet" href="./prism.css" />
    <link rel="stylesheet" href="./embed.css" />
    <title>Prism demo</title>
  </head>
  <body>
    <div id="root"></div>
    <script src="./embed.js"></script>
  </body>
</html>
`,
);
console.log(`✓ wrote ${out.replace(root + "/", "")}/{embed.js, prism.css, embed.css, index.html}`);
