// GENERATED by build-embed.mjs — do not edit.
import c_alert from "./alert.jsx";
import c_avatar from "./avatar.jsx";
import c_badge from "./badge.jsx";
import c_banner from "./banner.jsx";
import c_barchart from "./barchart.jsx";
import c_breadcrumb from "./breadcrumb.jsx";
import c_button from "./button.jsx";
import c_card from "./card.jsx";
import c_checkbox from "./checkbox.jsx";
import c_datepicker from "./datepicker.jsx";
import c_disclosure from "./disclosure.jsx";
import c_grid from "./grid.jsx";
import c_icon from "./icon.jsx";
import c_image from "./image.jsx";
import c_linechart from "./linechart.jsx";
import c_liquidglass from "./liquidglass.jsx";
import c_list from "./list.jsx";
import c_material from "./material.jsx";
import c_menu from "./menu.jsx";
import c_modal from "./modal.jsx";
import c_navbar from "./navbar.jsx";
import c_pagecontrol from "./pagecontrol.jsx";
import c_popover from "./popover.jsx";
import c_progressbar from "./progressbar.jsx";
import c_progressring from "./progressring.jsx";
import c_radio from "./radio.jsx";
import c_searchfield from "./searchfield.jsx";
import c_segmentedcontrol from "./segmentedcontrol.jsx";
import c_select from "./select.jsx";
import c_sheet from "./sheet.jsx";
import c_skeleton from "./skeleton.jsx";
import c_slider from "./slider.jsx";
import c_spinner from "./spinner.jsx";
import c_stateview from "./stateview.jsx";
import c_stepper from "./stepper.jsx";
import c_switch from "./switch.jsx";
import c_tabbar from "./tabbar.jsx";
import c_table from "./table.jsx";
import c_tabs from "./tabs.jsx";
import c_tag from "./tag.jsx";
import c_textarea from "./textarea.jsx";
import c_textfield from "./textfield.jsx";
import c_themeprovider from "./themeprovider.jsx";
import c_toast from "./toast.jsx";
import c_tooltip from "./tooltip.jsx";
import c_wheelpicker from "./wheelpicker.jsx";

export default {
  "alert": c_alert,
  "avatar": c_avatar,
  "badge": c_badge,
  "banner": c_banner,
  "barchart": c_barchart,
  "breadcrumb": c_breadcrumb,
  "button": c_button,
  "card": c_card,
  "checkbox": c_checkbox,
  "datepicker": c_datepicker,
  "disclosure": c_disclosure,
  "grid": c_grid,
  "icon": c_icon,
  "image": c_image,
  "linechart": c_linechart,
  "liquidglass": c_liquidglass,
  "list": c_list,
  "material": c_material,
  "menu": c_menu,
  "modal": c_modal,
  "navbar": c_navbar,
  "pagecontrol": c_pagecontrol,
  "popover": c_popover,
  "progressbar": c_progressbar,
  "progressring": c_progressring,
  "radio": c_radio,
  "searchfield": c_searchfield,
  "segmentedcontrol": c_segmentedcontrol,
  "select": c_select,
  "sheet": c_sheet,
  "skeleton": c_skeleton,
  "slider": c_slider,
  "spinner": c_spinner,
  "stateview": c_stateview,
  "stepper": c_stepper,
  "switch": c_switch,
  "tabbar": c_tabbar,
  "table": c_table,
  "tabs": c_tabs,
  "tag": c_tag,
  "textarea": c_textarea,
  "textfield": c_textfield,
  "themeprovider": c_themeprovider,
  "toast": c_toast,
  "tooltip": c_tooltip,
  "wheelpicker": c_wheelpicker,
};
